const imagens = [
  {
    id: 1,
    src: '/images/construcoes/B01.jpg',
    alt: 'Construção 01',
    descricao: 'Corpo e braço em cedro rosa; Escala em imbuia; Captadores Seymour Duncan; Trastes Dunlop Jumbo',
  },
  {
    id: 2,
    src: '/images/construcoes/B02.jpg',
    alt: 'Construção 02',
    descricao: 'Corpo em marupá; braço em tauari; escala em pau ferro; captadores Malagoli',
  },
  {
    id: 3,
    src: '/images/construcoes/B03.jpg',
    alt: 'Construção 03',
    descricao: 'Bloco central em pinus; asas em cedro rosa; escala em imbuia; captador single',
  },
  {
    id: 4,
    src: '/images/construcoes/B04.jpg',
    alt: 'Construção 04',
    descricao: 'Corpo e braço em mogno; escala em ébano; captadores Seymour Duncan; trastes jumbo',
  },
  {
    id: 5,
    src: '/images/construcoes/B05.jpg',
    alt: 'Construção 05',
    descricao: 'Guitarra baiana 6 cordas; Corpo em cedro rosa; braço em mogno; escala em imbuia; captador GFS',
  },
  {
    id: 6,
    src: '/images/construcoes/B06.jpg',
    alt: 'Construção 06',
    descricao: 'Corpo em cedro e laterais em pinus; braço em grápia; escala em ipê; traste jumbo de inox; ponte e captacão Wilkinson',
  },
  {
    id: 7,
    src: '/images/customizacoes/tommy.jpg',
    alt: 'Custom TommyThayer',
    descricao: 'Guitarra Dolphin foi customizada para ficar no estilo da Gibson Les Paul signature do Tommy Thayer (Kiss).',
  },
  {
    id: 8,
    src: '/images/customizacoes/budokkan.jpg',
    alt: 'Custom Buddokan',
    descricao: 'Guitarra Dolphin foi customizada para ter aparência semelhante a Gibson Les Paul Budokkan do Ace Frehley (Kiss).',
  },
  {
    id: 9,
    src: '/images/customizacoes/five.jpg',
    alt: 'Custom Bass 5 Strings',
    descricao: 'Baixo Dolphin foi feito um novo braço e customizado de 4 para 5 cordas, madeira do braço em imbuia.',
  },
  {
    id: 10,
    src: '/images/customizacoes/supersonic.jpg',
    alt: 'Custom Supersonic',
    descricao: 'Guitarra Giannini Supersonic dos anos 60 foi recuperada e a pintura foi feita para se aproximar da pintura original da mesma a época.',
  },
  {
    id: 11,
    src: '/images/customizacoes/neon.jpg',
    alt: 'Custom Neon',
    descricao: 'Escudo da guitarra foi customizado com material que brilha ao estar sob luz negra para ter um efeito neon no palco',
  },
  {
    id: 12,
    src: '/images/manutencoes/01.jpg',
    alt: 'Manutenção 01',
    descricao: '',
  },
  {
    id: 13,
    src: '/images/manutencoes/02.jpg',
    alt: 'Manutenção 02',
    descricao: '',
  },
  {
    id: 14,
    src: '/images/manutencoes/03.jpg',
    alt: 'Manutenção 03',
    descricao: '',
  },
  {
    id: 15,
    src: '/images/manutencoes/04.jpg',
    alt: 'Manutenção 04',
    descricao: '',
  },
  {
    id: 16,
    src: '/images/manutencoes/05.jpg',
    alt: 'Manutenção 05',
    descricao: '',
  },
  {
    id: 17,
    src: '/images/manutencoes/06.jpg',
    alt: 'Manutenção 06',
    descricao: '',
  },
  {
    id: 18,
    src: '/images/manutencoes/07.jpg',
    alt: 'Manutenção 07',
    descricao: '',
  },
  {
    id: 19,
    src: '/images/manutencoes/08.jpg',
    alt: 'Manutenção 08',
    descricao: '',
  },
  {
    id: 20,
    src: '/images/manutencoes/09.jpg',
    alt: 'Manutenção 09',
    descricao: '',
  },
  {
    id: 21,
    src: '/images/manutencoes/10.jpg',
    alt: 'Manutenção 10',
    descricao: '',
  },
  {
    id: 22,
    src: '/images/manutencoes/11.jpg',
    alt: 'Manutenção 11',
    descricao: '',
  },
  {
    id: 23,
    src: '/images/manutencoes/12.jpg',
    alt: 'Manutenção 12',
    descricao: '',
  },
];

export default imagens;
